# Generated by Django 3.1.4 on 2023-05-17 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_order_deliverytime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='deliveryTime',
        ),
    ]
