products = [
    {
        '_id': '1',
        'name': 'Airpods 2',
        'image': '/images/airpods.jpg',
        'description':
        'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working',
        'brand': 'Apple',
        'category': 'Electronics',
        'price': 89.99,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    },
    {
        '_id': '2',
        'name': 'iPhone 11 Pro 256GB',
        'image': '/images/phone.jpg',
        'description':
        'Introducing the iPhone 11 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life',
        'brand': 'Apple',
        'category': 'Electronics',
        'price': 599.99,
        'countInStock': 0,
        'rating': 4.0,
        'numReviews': 8,
    },
    {
        '_id': '3',
        'name': 'Cannon EOS 80D DSLR Camera',
        'image': '/images/camera.jpg',
        'description':
        'Characterized by versatile imaging specs, the Canon EOS 80D further clarifies itself using a pair of robust focusing systems and an intuitive design',
        'brand': 'Cannon',
        'category': 'Electronics',
        'price': 929.99,
        'countInStock': 5,
        'rating': 3,
        'numReviews': 12,
    },
    {
        '_id': '4',
        'name': 'Sony Playstation 4 Pro White Version',
        'image': '/images/playstation.jpg',
        'description':
        'The ultimate home entertainment center starts with PlayStation. Whether you are into gaming, HD movies, television, music',
        'brand': 'Sony',
        'category': 'Electronics',
        'price': 399.99,
        'countInStock': 11,
        'rating': 5,
        'numReviews': 12,
    },
    {
        '_id': '5',
        'name': 'Logitech G-Series Gaming Mouse',
        'image': '/images/mouse.jpg',
        'description':
        'Get a better handle on your games with this Logitech LIGHTSYNC gaming mouse. The six programmable buttons allow customization for a smooth playing experience',
        'brand': 'Logitech',
        'category': 'Electronics',
        'price': 49.99,
        'countInStock': 7,
        'rating': 3.5,
        'numReviews': 10,
    },
    {
        '_id': '6',
        'name': 'Amazon Echo Dot 3rd Generation',
        'image': '/images/alexa.jpg',
        'description':
        'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
        'brand': 'Amazon',
        'category': 'Electronics',
        'price': 29.99,
        'countInStock': 0,
        'rating': 4,
        'numReviews': 12,
    },
    {
        '_id': '7',
        'name': 'Samsung Galaxy S21',
        'image': '/images/galaxy.jpg',
        'description': 'Experience the power of the Samsung Galaxy S21. With its stunning display, powerful processor, and advanced camera system, it takes smartphone technology to the next level.',
        'brand': 'Samsung',
        'category': 'Electronics',
        'price': 799.99,
        'countInStock': 8,
        'rating': 4.7,
        'numReviews': 15,
    },
    {
        '_id': '8',
        'name': 'Nike Air Max 270',
        'image': '/images/airmax.jpg',
        'description': 'Step up your sneaker game with the Nike Air Max 270. Featuring a comfortable and stylish design, it provides maximum cushioning and support for all-day wear.',
        'brand': 'Nike',
        'category': 'Fashion',
        'price': 129.99,
        'countInStock': 3,
        'rating': 4.3,
        'numReviews': 9,
    },
    {
        '_id': '9',
        'name': 'KitchenAid Stand Mixer',
        'image': '/images/mixer.jpg',
        'description': 'Take your culinary skills to the next level with the KitchenAid Stand Mixer. Its powerful motor and versatile attachments make it the perfect tool for baking and cooking enthusiasts.',
        'brand': 'KitchenAid',
        'category': 'Home & Kitchen',
        'price': 299.99,
        'countInStock': 6,
        'rating': 4.8,
        'numReviews': 18,
    },
    {
        '_id': '10',
        'name': 'Fitbit Versa 3 Smartwatch',
        'image': '/images/fitbit.jpg',
        'description': 'Track your fitness goals and stay connected with the Fitbit Versa 3 Smartwatch. It features built-in GPS, heart rate monitoring, and a variety of exercise modes to help you stay active.',
        'brand': 'Fitbit',
        'category': 'Electronics',
        'price': 199.99,
        'countInStock': 4,
        'rating': 4.5,
        'numReviews': 11,
    },
    {
        '_id': '11',
        'name': 'Levi\'s 501 Original Jeans',
        'image': '/images/jeans.jpg',
        'description': 'Get the timeless style of Levi\'s 501 Original Jeans. Made from high-quality denim, they offer a classic fit and unmatched durability for everyday wear.',
        'brand': 'Levi\'s',
        'category': 'Fashion',
        'price': 79.99,
        'countInStock': 9,
        'rating': 4.2,
        'numReviews': 13,
    },
]
